name: CI
run-name: SvennD Blog Update
on:
  push:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash
    
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.115.1
    
    steps:
      - name: Checkout the current branch
        uses: actions/checkout@v3.5.3
        with:
          submodules: recursive
          fetch-depth: 0
          
      - name: Initialize the ssh-agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: | 
              ${{ secrets.SSH_PRIVATE_KEY }}
              ${{ secrets.HUGO_CODE_KEY }}

      - name: Clone repository
        run: git clone git@github.com:svennd/svenn_clean.git
      
      - name: Install Hugo
        run: sudo snap install hugo

      - name: Build the hugo blog
        run: cd svenn_clean && npm i && HUGO_ENVIRONMENT=production hugo --gc

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
          
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
